//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string TZ { get; set; }
        public Nullable<System.DateTime> BornDate { get; set; }
        public string Genus { get; set; }
        public string HMO { get; set; }
        public Nullable<int> NumChildren { get; set; }
        public int Id { get; set; }
    
        public virtual Kid Kid { get; set; }
    }
}
